[2014-09-04 16:25:32] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /media/tiago/Novo volume/Backup Linux/2/www/html/SigNovo/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php:146
Stack trace:
#0 /media/tiago/Novo volume/Backup Linux/2/www/html/SigNovo/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1021): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /media/tiago/Novo volume/Backup Linux/2/www/html/SigNovo/vendor/laravel/framework/src/Illuminate/Routing/Router.php(989): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /media/tiago/Novo volume/Backup Linux/2/www/html/SigNovo/vendor/laravel/framework/src/Illuminate/Routing/Router.php(968): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /media/tiago/Novo volume/Backup Linux/2/www/html/SigNovo/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(738): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /media/tiago/Novo volume/Backup Linux/2/www/html/SigNovo/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(708): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /media/tiago/Novo volume/Backup Linux/2/www/html/SigNovo/vendor/laravel/framework/src/Illuminate/Http/FrameGuard.php(38): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /media/tiago/Novo volume/Backup Linux/2/www/html/SigNovo/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true)
#7 /media/tiago/Novo volume/Backup Linux/2/www/html/SigNovo/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#8 /media/tiago/Novo volume/Backup Linux/2/www/html/SigNovo/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#9 /media/tiago/Novo volume/Backup Linux/2/www/html/SigNovo/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#10 /media/tiago/Novo volume/Backup Linux/2/www/html/SigNovo/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#11 /media/tiago/Novo volume/Backup Linux/2/www/html/SigNovo/public/index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2014-09-04 16:26:29] production.ERROR: exception 'InvalidArgumentException' with message 'Command "publish" is not defined.

Did you mean one of these?
    view:publish
    asset:publish
    config:publish
    migrate:publish
    generate:publish-templates' in /media/tiago/Novo volume/Backup Linux/2/www/html/SigNovo/vendor/symfony/console/Symfony/Component/Console/Application.php:562
Stack trace:
#0 /media/tiago/Novo volume/Backup Linux/2/www/html/SigNovo/vendor/symfony/console/Symfony/Component/Console/Application.php(188): Symfony\Component\Console\Application->find('publish')
#1 /media/tiago/Novo volume/Backup Linux/2/www/html/SigNovo/vendor/symfony/console/Symfony/Component/Console/Application.php(121): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /media/tiago/Novo volume/Backup Linux/2/www/html/SigNovo/artisan(59): Symfony\Component\Console\Application->run()
#3 {main} [] []
